apiVersion: v2
appVersion: 1.1.0
description: Helm chart for the aerios Identity Manager based on Keycloak
name: idm
type: application
version: 1.1.0
keywords:
  - ravaga-helm-chart-generator
  - aerios
  - keycloak
  - oauth2.0
  - cybersecurity
  - idm
