apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.svc.headless" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.database.service.ports.db.port }}
      targetPort: {{ .Values.database.service.ports.db.targetPort }}
      protocol: {{ .Values.database.service.ports.db.protocol }}
  selector:
    {{- include "database.selectorLabels" . | nindent 4 }}