apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.ports.db.port }}
      targetPort: {{ .Values.database.service.ports.db.targetPort }}
      protocol: {{ .Values.database.service.ports.db.protocol }}
      {{- if and (or (eq .Values.database.service.type "NodePort") (eq .Values.database.service.type "LoadBalancer")) (not (empty .Values.database.service.ports.db.nodePort)) }}
      nodePort: {{ .Values.database.service.ports.db.nodePort }}
      {{ end }}
  selector:
    {{- include "database.selectorLabels" . | nindent 4 }}
