{{- if and .Values.keycloak.tls.enabled (not .Values.keycloak.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.keycloak.tls.certs }}
  cert.pem: {{ .cert | quote }}
  key.pem: {{ .key | quote }}
  {{- end }}
{{- end }}