apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  {{- if not .Values.keycloak.autoscaling.enabled }}
  replicas: {{ .Values.keycloak.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if and .Values.keycloak.tls.enabled (not .Values.keycloak.tls.existingSecret) }}
      annotations:
        checksum/keycloak-cert: {{ include (print $.Template.BasePath "/keycloak/cert-secret.yaml") . | sha256sum }}
      {{- end }}
      labels:
        {{- include "keycloak.labels" . | nindent 8 }}
    spec:
      {{- with .Values.keycloak.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.chartNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.chartNodeSelector }}
        {{- with .Values.keycloak.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.keycloak.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.keycloak.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.keycloak.podSecurityContext | nindent 8 }}
      containers:
        - name: keycloak
          securityContext:
            {{- toYaml .Values.keycloak.securityContext | nindent 12 }}
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.keycloak.service.ports.keycloak.containerPort }}
              protocol: {{ .Values.keycloak.service.ports.keycloak.protocol }}
            {{- if .Values.keycloak.tls.enabled }}
            - containerPort: {{ .Values.keycloak.service.ports.https.containerPort }}
              protocol: {{ .Values.keycloak.service.ports.https.protocol }}
            {{- end }}
          resources:
            {{- toYaml .Values.keycloak.resources | nindent 12 }}
          env:
            - name: DB_ADDR
              value: {{ include "database.fullname" . }}
            {{- with .Values.keycloak.envVars }}
            - name: PROXY_ADDRESS_FORWARDING
              value: {{ .proxyAddressForwarding | quote }}
            - name: DB_DATABASE
              value: {{ .dbDatabase | quote }}
            - name: DB_PASSWORD
              value: {{ .dbPassword | quote }}
            - name: DB_SCHEMA
              value: {{ .dbSchema | quote }}
            - name: DB_USER
              value: {{ .dbUser | quote }}
            - name: DB_VENDOR
              value: {{ .dbVendor | quote }}
            - name: KEYCLOAK_PASSWORD
              value: {{ .keycloakPassword | quote }}
            - name: KEYCLOAK_USER
              value: {{ .keycloakUser | quote }}
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: {{ .hostnamestricthttps | quote }}
            {{- if .httpRelativePath }}
            - name: KC_HTTP_RELATIVE_PATH 
              value: {{ .httpRelativePath }}
            {{- end }}
            {{- end }}
            {{- if .Values.keycloak.tls.enabled }}
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: "/etc/certs/cert.pem"
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: "/etc/certs/key.pem"
            {{- end }}
          {{- if .Values.keycloak.tls.enabled }}
          volumeMounts:
            - name: keycloak-cert
              mountPath: /etc/certs
              readOnly: true
          {{- end }}
      {{- if .Values.keycloak.tls.enabled }}
      volumes:
        - name: keycloak-cert
          secret:
            {{- if .Values.keycloak.tls.existingSecret }}
            secretName: {{ .Values.keycloak.tls.existingSecret }}
            {{- else}}
            secretName: {{ include "keycloak.fullname" . }}-secret
            {{- end }}
            items:
              - key: cert.pem
                path: cert.pem
              - key: key.pem
                path: key.pem
      {{- end }}
