apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
    - name: http
      port: {{ .Values.keycloak.service.ports.keycloak.port }}
      targetPort: {{ .Values.keycloak.service.ports.keycloak.targetPort }}
      protocol: {{ .Values.keycloak.service.ports.keycloak.protocol }}
      {{- if and (or (eq .Values.keycloak.service.type "NodePort") (eq .Values.keycloak.service.type "LoadBalancer")) (not (empty .Values.keycloak.service.ports.keycloak.nodePort)) }}
      nodePort: {{ .Values.keycloak.service.ports.keycloak.nodePort }}
      {{ end }}
    {{- if .Values.keycloak.tls.enabled }}
    - name: https
      port: {{ .Values.keycloak.service.ports.https.port }}
      targetPort: {{ .Values.keycloak.service.ports.https.targetPort }}
      protocol: {{ .Values.keycloak.service.ports.https.protocol }}
      {{- if and (or (eq .Values.keycloak.service.type "NodePort") (eq .Values.keycloak.service.type "LoadBalancer")) (not (empty .Values.keycloak.service.ports.https.nodePort)) }}
      nodePort: {{ .Values.keycloak.service.ports.https.nodePort }}
      {{ end }}
    {{- end }}
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
